version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
      timezone: Japan
    reviewers:
      - MorrisonCole
    assignees:
      - MorrisonCole
    versioning-strategy: increase
    labels:
      - "automerge"
